### ISSUE TITLE
Add parallax scroll

### ISSUE THREAD

**Issue by stenwall** [chas-academy/u02-redesign-unit7#28]
Use full width container (see index.html info news)

**Comment by axelra82** [comment]
# Tip regarding parallax 🤓
Remember that this requirement is for a **HTML & CSS based project** 😉
Although JS has been mentioned as _"OK"_, this effect (parallax) should probably be done **purely in CSS**, i.e. _without any JS_.

JS is the easier (and probably still the more common) route when doing parallax, in terms of precision. One problem I've personally encountered with CSS parallax (using `overflow: scroll-y`) is that it can result in double scrollbars.

[Here is an interesting post with details regarding CSS parallax](https://developers.google.com/web/updates/2016/12/performant-parallaxing) 👍

**EDIT**
[Here is another article about CSS Parallax](https://medium.com/@dailyfire/pure-css-parallax-simple-tricks-da102d0ffdb9)
Ironically the page that the article references for "demo" doesn't have any parallax (at least not in latest macOS Safari, Chrome or Firefox). Would be interesting to note if it does have parallax  in other browsers/OS. This could be something worth looking into since something might have changed since the articles above were written 🤷‍♂️

**NOTE:** It looks like the first post is from 2016, so be aware that some things might have changed. The principal and logic however, still stands.

**SIDE NOTE:** Trying to find a date on any technical/code related post, as fast as possible/initially (i.e. before putting to much effort in to it), is always a good and fast way of deciding how relevant it might still be 😄
