### ISSUE TITLE
Fix working link from page-scss-file

### ISSUE THREAD

**Issue by stenwall** [chas-academy/u02-redesign-unit7#34]
# **Help needed!**
When editing in `_publikationer.scss`, it's not compiling and I can't see my changes in live server. Is there a way of fixing this? I've looked over all the links you made @axelra82, but I can't work out why everything from `_index.scss` is compiling and mine isn't. It's linked in `style.scss` and according to VSC the link is working.

**UPDATE:** I tried working in the `_index.scss` (just temporarily, without commits), just to see what I was doing when I made changes in the css, but that's not working either. My plan right now is to comment out all the code related to GitHub pages and somehow make a link manually. Not sure how that's going to work though since nothing seems to be compiling in `style.min.css`. Do I have to write everything in plain CSS instead and not use sass? Feels like it would make everything more difficult. I've spent the last hours trying to figure out what to do and would be really grateful for any help 😢 

**UPDATE 2:** Managed to somehow work around it by updating the `style.scss` every time I changed something in `_publikationer.scss`. Since it's really unpractical to work that way, my plan right now is to write my code in `style.scss` and when I want to commit i erase it from there and paste it into `_publikationer.scss`. Still glad to hear a better solution!

**Comment by Oskar-Mikael** [comment]
I Think it will only compile after you have saved the style.scss file (that has all the imports of the different scss files)

**Comment by axelra82** [comment]
@Oskar-Mikael is correct 👍
The reason for this comes from **the restrictions** in the live sass compiler plug-in settings (that we use).

If the restrictions weren't there, we would end up with a corresponding css file for each scss file **every time you save a scss file** 😊
_This is a little wonky behavior in live sass compiler that I haven't been able to work around (mostly because of **lack of time and interest** 😂 Since I rarely use it (I.e. work in pure HTML & CSS stacks 😅))._

So as it is now, with the current settings, you have to save the **_your-style.scss** file first, then the **styles.scss**, this will give you a new **style.min.css** with the updated styling 👌

My workaround for this has been to have the style.scss file open in a tab when I'm working on styling, that way it's just an extra click (on the tab) and save (remember the order though, first save _your-style.scss, then save style.scss. Also, make sure that _your-style.scss is properly imported in style.scss)  😊

**Comment by axelra82** [comment]
@stenwall just wanted to check in on this issue and see if you found a solution? 🤔
If not, maybe we can close it since we'll probably need to spend the next couple of days on finishing up the project? 😄

**Comment by stenwall** [comment]
You're right, I'm closing it! :)
